
CREATE TABLE `BlogPorteFolio`.`Articles` ( `idArticle` INT NOT NULL AUTO_INCREMENT , `date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP , `titre` TEXT NOT NULL , `sousTitre` TEXT NULL DEFAULT NULL , `description` TEXT NULL DEFAULT NULL , `article` TINYINT NOT NULL , `themeId` INT NOT NULL , PRIMARY KEY (`idArticle`)) ENGINE = InnoDB;

CREATE TABLE `BlogPorteFolio`.`Projets` ( `idProjet` INT NOT NULL AUTO_INCREMENT , `date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP , `titre` TEXT NOT NULL , `lienTest` TEXT NULL DEFAULT NULL, `description` TEXT NOT NULL , `techno` TEXT NULL DEFAULT NULL , PRIMARY KEY (`idProjet`)) ENGINE = InnoDB;

CREATE TABLE `BlogPorteFolio`.`Theme` ( `idTheme` INT NOT NULL AUTO_INCREMENT , `theme` VARCHAR(70) NOT NULL , `date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`idTheme`)) ENGINE = InnoDB;

CREATE TABLE `BlogPorteFolio`.`Images` ( `idImage` INT NOT NULL AUTO_INCREMENT , `image` TEXT NOT NULL , `date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP , `articleId` INT NULL DEFAULT NULL , `projetId` INT NULL DEFAULT NULL , PRIMARY KEY (`idImage`)) ENGINE = InnoDB;